# Generated by Django 2.2.1 on 2019-06-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190609_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text="write your title use(hypen-), don't use space. Ex: Bangladesh-is-a"),
        ),
    ]
